---
id: sezemi-2014-readable-code-2-code-change
base_name: next-step
tags:
- rabbit
- readable-code
- sezemi
presentation_date: 2014-07-06
version: 2014.7.6.1
licenses:
- CC BY-SA 4.0
slideshare_id: sezemi-2014-readable-code-2-code-change
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Kouhei Sutou
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: kou
  speaker_deck_user: kou
