---
id: sezemi-2015-readable-code-introduction
base_name: how-to-proceed
tags:
- rabbit
- readable-code
- sezemi
presentation_date: 2015-06-06
version: 2015.6.6.0
licenses:
- CC BY-SA 4.0
slideshare_id: sezemi-2015-readable-code-introduction
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Kouhei Sutou
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: kou
  speaker_deck_user: kou
